### ISSUE TITLE
[Feature]: flatpak distribution

### ISSUE THREAD

**Issue by garyttierney** [garyttierney/me3#395]
Accompanying issue to #173, while solving that we should start packaging for flatpak. We can publish to OBS.

**Comment by garyttierney** [comment]
> Packaged me3 as a Steam Utility extension com.valvesoftware.Steam.Utility.me3

Ah, interesting. I wasn't aware we could do this via flatpak runtime extensions. Would you mind explaining a bit about how this works? I imagined it might just be overlaying another filesystem on top of the Steam container, but the note below about requiring a pid1 wrapper makes me wonder if it's not so simple. Is this only for the `me3 launch` case and not with `me3 wrap`?

> I added a wrap subcommand that integrates with Steam's %command% mechanism instead, allowing me to launch games on linux using custom launch options such as:

It's not ideal to put the profile name in the Steam launch options (I do wonder if Steam would pass environment variables through from `steam steam://rungameid/...` though), but I'd be happy to ship the `wrap` command anyway. It's useful if only to show you the command me3 _would_ run for troubleshooting and debugging.

I'm curious about the Steam input breakage, I'll see if I can reproduce that and find out if it's relevant at all to what's going on with Steam Deck in game mode.

Thanks for putting in the effort to look into this, it's been on the todo list for a while.

**Comment by thanosapollo** [comment]
> Would you mind explaining a bit about how this works?

Steam Utility extensions mount at `/app/utils/me3/` **inside** Steam's sandbox, sharing its namespace (IPC, display, network).  A standalone flatpak can't reach Steam's IPC sockets across container boundaries, so overlay/controller/session break and even the game won't even launch since proton/pressure-vessel depend on Steam's runtime environment being accessible. Utility extension sidesteps that entirely.

The wrinkle is pressure-vessel: When SLR launches a game, it creates a nested bubblewrap container where `/app` gets remapped to `/run/parent/app`. So paths to `me3-launcher.exe` need rewriting before being passed to proton. The existing `/run/host` remapping for `/usr` etc was already there, I just added the `/app` case.

>  but the note below about requiring a pid1 wrapper makes me wonder if it's not so simple.

PID 1 wrapper is only for `me3 launch` where me3 is the container entrypoint. PID 1 has special kernel signal/zombie semantics that break the nested process tree. With wrap, Steam is already running and me3 is a child process so it's not an issue.

> It's not ideal to put the profile name in the Steam launch options

Agreed. `wrap` already auto-detects the game from SteamAppId (which Steam sets before expanding `%command%`), so `-g` isn't needed.  For the profile, a config mapping game => default profile would let `me3 wrap -- %command%` work with zero flags.  Happy to look into that if you'd want it upstream.

> I'm curious about the Steam input breakage

Curious what you find.  On my end (Guix + flatpak steam), `me3 launch` consistently has no controller input, `me3 wrap` works fine through steam input for Nightreign.  The issue on my end seems to be that Steam does not set up its input session when the game is launched outside its pipeline.

**Comment by garyttierney** [comment]
I'll have a proper look over the changes over the weekend, but I think we want to include most of them and definitely the infrastructure for building the flatpak runtime extension at the least.

I'd like to explore a few options before we commit to this `me3 wrap` approach for flatpak, specifically:

- There was an issue with the overlay renderer not being injected by me3 that is now fixed in main. I wonder if this fixes `me3 launch` within the Steam namespaces?
  - If it doesn't I'd like to look into exactly why that doesn't work. If we're able to run `me3 launch` within the same container as Steam I can't see any reason why it wouldn't work with the latest LD_PRELOAD fix.
- If the above is absolutely impossible to get working, would patching the users steam configuration to include the equivalent to `me3 wrap` in the launch options be a feasible approach? Ideally we wouldn't actually replace that file and could bind mount over it temporarily

**Comment by thanosapollo** [comment]
`LD_PRELOAD` fix works, overlay renderer loads.  Controllers still don't
work because Steam Input session setup is independent of the
overlay. `wrap` remains necessary for full Steam integration.

> tested on the latest main branch with flatpak and only the `/app` remap patched

Users can still use:

```
$ flatpak run --command=me3 com.valvesoftware.Steam launch -g nightreign -p arena
````
*which is awkward as the default imho*

if they need to use `launcher`, but I don't think it should be the
recommended way to do so in Linux via flatpak.

Is there a use case where bypassing Steam's launch pipeline entirely
(via `launch`) is preferable?  If not, `wrap` seems like the right
default for Linux/Flatpak, with `launch` available as fallback for
debugging.

> would patching the users steam configuration to include the equivalent to me3 wrap in the launch options be a feasible approach?

- patching `localconfig.vdf`: doable but fragile.  Steam rewrites that file often and vdf format is annoying to parse/modify reliably.
- Bind mounting over it:  Might work outside of flatpak, but I don't think we have the permissions to bind over steam's files from inside.

I think those add complexity for something that's a one-time user action, setting launcher options, the manual step is minimal and easy to undone.
